network_name: "Vietnam_Construction_Net"
domain: "khoai.local"

# Cấu hình chung cho Docker Image
image_base: "golang:1.22-alpine"
image_tag: "v1.0.0"
registry: "registry.duongess.com/khoai-chain"

nodes:
  - name: "node_vingroup"
    port: 9000
    db_path: "/data/vin_db"
    peers: [] # Node đầu tiên, không có peer
    chaincodes:


  - name: "node_coteccons"
    port: 9001
    db_path: "/data/coteccons_db"
    peers:
      - "node_vingroup:9000"
    chaincodes:

  - name: "node_thachthat"
    port: 9002
    db_path: "/data/thachthat_db"
    peers:
      - "node_coteccons:9001"
    chaincodes:
      - name: nongnghiep
        package: khoai-chain/contracts/nongnghiep
        constructor: NewNongNghiepContract
